table dim_Date
	lineageTag: 78a8554d-0a78-42cf-ba12-d6fd9828b172
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: 98f95b9f-db53-492e-9245-69ac12b7f666
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: ba4bc7de-aac2-4730-986c-a45fd501ef69
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 0c84ec1b-b9e4-4b07-82f9-85ff361aaf29
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 21e68e27-23fb-4c4c-8227-b65255abfce2
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: Month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Year-Month
		dataType: string
		lineageTag: d456f68f-8871-4f42-aca9-d77b9cb3abaf
		summarizeBy: none
		sourceColumn: Year-Month
		sortByColumn: Year-Month-Number

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 999109ae-4a43-4a49-84b9-5a02682f1da2
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column 'Week of Year'
		dataType: int64
		formatString: 0
		lineageTag: da92ed7d-fd68-4060-8f95-1991312552f8
		summarizeBy: none
		sourceColumn: Week of Year

		annotation SummarizationSetBy = Automatic

	column 'Start of Week'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e845db2e-d3cf-4722-a471-9027b2f32886
		summarizeBy: none
		sourceColumn: Start of Week

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 15273a50-cb93-4d2a-86bc-9f9f1ad0e4a6
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		lineageTag: a7c5527f-1476-4126-883f-c79ffe4b0f81
		summarizeBy: none
		sourceColumn: Day Name

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Day Number'
		dataType: int64
		formatString: 0
		lineageTag: 1f5dd1a3-d86a-45a3-81b5-e07147204cb8
		summarizeBy: none
		sourceColumn: Day Number

		annotation SummarizationSetBy = Automatic

	column Year-Month-Number
		dataType: int64
		formatString: 0
		lineageTag: 39f49d8d-946b-412a-9976-f0cb076d80ab
		summarizeBy: none
		sourceColumn: Year-Month-Number

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 37b1ebee-0339-47c4-8a69-62745bc25b2a

		level Date
			lineageTag: d75231bc-f23b-48a9-a062-b71aeaf18db3
			column: Date

		level Year-Month
			lineageTag: e508f848-fa10-4b94-8a73-303c47594444
			column: Year-Month

	partition dim_Date = m
		mode: import
		source =
				let
				    Source = #date(2023, 1, 1),
				    EndDate = Date.EndOfMonth(DateTime.Date(DateTime.LocalNow())),
				    DayCount = Duration.Days(EndDate - Source) + 1,
				    ListOfDates = List.Dates(Source, DayCount, #duration(1, 0, 0, 0)),
				    #"Converted to Table" = Table.FromList(ListOfDates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),
				    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([Date]), Int64.Type),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Month", "Month Name", each Date.MonthName([Date]), type text),
				    #"Inserted Year-Month" = Table.AddColumn(#"Inserted Month Name", "Year-Month", each Date.ToText([Date], "yyyy-MM"), type text),
				    #"Inserted Quarter" = Table.AddColumn(#"Inserted Year-Month", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date])), type text),
				    #"Inserted Week of Year" = Table.AddColumn(#"Inserted Quarter", "Week of Year", each Date.WeekOfYear([Date]), Int64.Type),
				    #"Inserted Start of Week" = Table.AddColumn(#"Inserted Week of Year", "Start of Week", each Date.StartOfWeek([Date], Day.Monday), type date),
				    #"Inserted Day" = Table.AddColumn(#"Inserted Start of Week", "Day", each Date.Day([Date]), Int64.Type),
				    #"Inserted Day Name" = Table.AddColumn(#"Inserted Day", "Day Name", each Date.DayOfWeekName([Date]), type text),
				    #"Inserted Day Number" = Table.AddColumn(#"Inserted Day Name", "Day Number", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added Year-Month-Number" = Table.AddColumn(#"Inserted Day Number", "Year-Month-Number", each [Year] * 100 + [Month], Int64.Type)
				in
				    #"Added Year-Month-Number"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

