table v_dim_customers_std
	lineageTag: a65f55b2-508b-41d2-bef5-6163e47086a2

	column 'Customer ID'
		dataType: string
		isHidden
		lineageTag: 13405997-6c73-42c6-ac95-70571eec919d
		summarizeBy: none
		sourceColumn: Customer ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Signup Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2488a9db-5c64-4913-9d6b-68395fa3d03f
		summarizeBy: none
		sourceColumn: Signup Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Customer Archetype'
		dataType: string
		lineageTag: 72e4da81-4719-4c7d-bdd5-3a5c033be263
		summarizeBy: none
		sourceColumn: Customer Archetype

		annotation SummarizationSetBy = Automatic

	column 'First Name'
		dataType: string
		lineageTag: 499191c0-fbd6-408d-a1b0-f311f55cf2d0
		summarizeBy: none
		sourceColumn: First Name

		annotation SummarizationSetBy = Automatic

	column 'Last Name'
		dataType: string
		lineageTag: e54a1553-1a9c-4392-bb34-e30ed34611e5
		summarizeBy: none
		sourceColumn: Last Name

		annotation SummarizationSetBy = Automatic

	column 'Full Name'
		dataType: string
		lineageTag: 5b5bf7d2-6e2b-40db-bd63-97f1a4d0c33f
		summarizeBy: none
		sourceColumn: Full Name

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 1b36dd56-59ea-46dd-a1a0-8755cc50d3ac
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: string
		lineageTag: d555d860-12fa-4a0b-9847-94ce202928a7
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 8fe65de1-5ee1-4412-af6b-e4cfd8507764
		summarizeBy: none
		sourceColumn: Country

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 9974c2c2-6a2e-4107-bc48-b9e329c6d09f
		summarizeBy: none
		sourceColumn: State

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: e456708a-0261-4085-9919-d46403c998b3
		summarizeBy: none
		sourceColumn: City

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Address
		dataType: string
		lineageTag: c288bc35-d35a-471a-834e-564869fe5347
		summarizeBy: none
		sourceColumn: Address

		annotation SummarizationSetBy = Automatic

	partition v_dim_customers_std = m
		mode: import
		source =
				let
				    Source = GoogleBigQuery.Database([Implementation="2.0"]),
				    #"kupferkanne-2026_Database" = Source{[Name="kupferkanne-2026",Kind="Database"]}[Data],
				    sales_Schema = #"kupferkanne-2026_Database"{[Name="sales",Kind="Schema"]}[Data],
				    v_dim_customers_std_View = sales_Schema{[Name="v_dim_customers_std",Kind="View"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(v_dim_customers_std_View,{{"SignupDate", "Signup Date"}, {"FullName", "Full Name"}, {"CustomerArchetype", "Customer Archetype"}, {"FirstName", "First Name"}, {"LastName", "Last Name"}, {"CustomerID", "Customer ID"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Exception

